name: Build Super Gold 97 German ROM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Systempackete aktualisieren
        run: |
          sudo apt update
          sudo ACCEPT_EULA=Y apt -y --fix-missing --allow-downgrades upgrade
          sudo apt -y --allow-downgrades install make g++-10 bison git python-is-python3 python3-pip bison pkg-config libpng-dev
          sudo pip install pypng

      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: RGBDS auschecken
        uses: actions/checkout@v4
        with:
          repository: gbdev/rgbds
          path: rgbds
          ref: 'v0.6.1'

      - name: RGBDS installieren
        run: |
          cd rgbds
          make Q=
          sudo make install

      - name: ROM bauen
        run: |
          make pokemon_sg97.gbc
        working-directory: .

      - name: Belegten Speicherplatz prüfen
        run: python3 tools/used_space.py

      - name: Freier Speicherplatz prüfen
        run: python3 tools/free_space.py

      - name: ROM-Datei hochladen
        uses: actions/upload-artifact@v4
        with:
          name: pokemon_sg97
          path: pokemon_sg97.gbc